spring.application.name=MarketIQb
spring.datasource.url=jdbc:postgresql://localhost:5432/market
spring.datasource.username=postgres
spring.datasource.password==Kunal537
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
